# Generated by Django 4.2.7 on 2024-01-28 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_marketplace', '0002_product_available_quantity_product_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
    ]
