# Generated by Django 4.2.7 on 2024-01-28 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_marketplace', '0003_remove_product_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='ingredients',
        ),
        migrations.RemoveField(
            model_name='product',
            name='weight_grams',
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
