# Generated by Django 4.2.7 on 2024-02-16 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wineries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='winery',
            name='region',
            field=models.CharField(blank=True, choices=[('Regiunea viticolă a dealurilor Moldovei', 'Regiunea viticolă a dealurilor Moldovei'), ('Regiunea viticolă a podișului Transilvaniei', 'Regiunea viticolă a podișului Transilvaniei'), ('Regiunea viticolă a dealurilor Munteniei și Olteniei', 'Regiunea viticolă a dealurilor Munteniei și Olteniei'), ('Regiunea viticolă a dealurilor Banatului', 'Regiunea viticolă a dealurilor Banatului'), ('Regiunea viticolă a Crișanei și Maramureșului', 'Regiunea viticolă a Crișanei și Maramureșului'), ('Regiunea viticolă a teraselor Dunării', 'Regiunea viticolă a teraselor Dunării'), ('Nisipurile și alte terenuri favorabile din sudul țării', 'Nisipurile și alte terenuri favorabile din sudul țării')], max_length=100, null=True),
        ),
    ]
